use std::process::ExitCode;
use crate::cli_args::ShotOp;
use crate::handlers::shot_edit::run_shot_edit;
use crate::handlers::shot_fix::run_shot_fix;
use crate::handlers::shot_fix_from_verify::run_shot_fix_from_verify;
use crate::handlers::shot_insert_into_scene::run_shot_insert_into_scene;
use crate::handlers::shot_search::run_shot_search;
use crate::handlers::shot_still::run_shot_still;
use crate::handlers::shot_txt2vid::run_shot_txt2vid;
use crate::handlers::shot_upscale::run_shot_upscale;
use crate::handlers::util::InsertIntoSceneArgs;

/// Top-level `wavelet shot <op>` dispatch.
pub fn run_shot(op: ShotOp) -> ExitCode {
    match op {
        ShotOp::Txt2Vid {
            prompt,
            backend,
            duration,
            aspect,
            negative,
            no_default_negatives,
            seed,
            variants,
            select,
            max_variants_cost,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_txt2vid(prompt, backend, duration, aspect, negative, no_default_negatives, seed, variants, select, max_variants_cost, dry_run, max_cost, cache, out, pretty),
        ShotOp::Still {
            prompt,
            backend,
            image_size,
            seed,
            variants,
            select,
            criteria,
            max_variants_cost,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_still(prompt, backend, image_size, seed, variants, select, criteria, max_variants_cost, dry_run, max_cost, cache, out, pretty),
        ShotOp::Search {
            query,
            backend,
            orientation,
            min_duration,
            max_duration,
            per_page,
            page,
            dry_run,
            max_cost,
            cache,
            pretty,
        } => run_shot_search(query, backend, orientation, min_duration, max_duration, per_page, page, dry_run, max_cost, cache, pretty),
        ShotOp::Fix {
            input,
            instruction,
            region,
            image_w,
            image_h,
            guidance,
            steps,
            seed,
            backend,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_fix(
            input, instruction, region, image_w, image_h, guidance, steps, seed, backend,
            dry_run, max_cost, cache, out, pretty,
        ),
        ShotOp::FixFromVerify {
            input,
            verify_report,
            backend,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_fix_from_verify(
            input,
            verify_report,
            backend,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        ),
        ShotOp::Upscale {
            input,
            model,
            target,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_upscale(input, model, target, dry_run, max_cost, cache, out, pretty),
        ShotOp::InsertIntoScene {
            product,
            scene,
            threshold,
            strict_identity,
            seed,
            backend,
            identity_backend,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        } => run_shot_insert_into_scene(InsertIntoSceneArgs {
            product,
            scene,
            threshold,
            strict_identity,
            seed,
            backend,
            identity_backend,
            dry_run,
            max_cost,
            cache,
            out,
            pretty,
        }),
        ShotOp::Edit {
            input,
            intent,
            out,
            report,
            max_attempts,
            max_cost,
            pass_threshold,
            planner_model,
            reviewer_model,
            dry_run,
        } => run_shot_edit(
            input,
            intent,
            out,
            report,
            max_attempts,
            max_cost,
            pass_threshold,
            planner_model,
            reviewer_model,
            dry_run,
        ),
    }
}
